### PR TITLE
ENH: rename 'TIFF' to 'SINGLE_TIFF'

### PR DESCRIPTION
**Pull request by CJ-Wright**
'TIFF' might not be the best name, so 'SINGLE_TIFF'. See #117

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Thanks!

**Comment by danielballan** [comment]
Doesn't this break things?

**Comment by tacaswell** [comment]
this went in yesterday so it has never been released and probably only breaks @CJ-Wright

**Comment by CJ-Wright** [comment]
Yes, this breaks all of my things. It is the equivalent of "HULK SMASH" to my code base. /s

Its fine though, a) I'll just fix things in a refactor on my side, b) I haven't started using this handler in filestore, I have it in my own repos as `TIFF`, so I can gracefully transition.

**Comment by tacaswell** [comment]
I would point out that this only affect the 'auto' registration.  You can still manually register the handler as 'TIFF'.

**Comment by CJ-Wright** [comment]
Thank you! I didn't think of that. None of my code which handles `TIFF` is running anywhere and all the dbs that currently have `TIFF` in them are legacy, so I am not super worried.

**Comment by CJ-Wright** [comment]
Speaking of auto-registration, is there a function which registers all the handlers in filestore?

**Comment by tacaswell** [comment]
It is in databroker https://github.com/NSLS-II/databroker/blob/master/databroker/handler_registration.py

**Comment by CJ-Wright** [comment]
Awesome, thank you!

**Pull request merged**
