### PR TITLE
FIX: db_connect docstring fix. Same as PR #92 in metadatastore

### PR DESCRIPTION
**Pull request by arkilic**

### CODE REVIEW

**Comment by tacaswell** [comment]
Why do we want to expose the ability to set the database properties into _every_ call?  It just gives a huge surface to silently ignore user input.

**Comment by danielballan** [comment]
I'm not sure part of this change you think is bad. You dislike @db_connect entirely? Do you like the way it currently blows away the docstrings?

**Comment by danielballan** [comment]
I agree it should warn the user when passing an option will do nothing, but this PR is an improvement over current behavior, unless I misunderstand your point.

**Comment by tacaswell** [comment]
I protest to popping the connection information from the kwargs,  I like the `@wraps` and the decorator in general.

**Comment by danielballan** [comment]
If you pass connection information down into the wrapped function it will complain that it did not expect to receive kwargs named "database" and "host."

**Comment by tacaswell** [comment]
Which I think is the correct behaviour as they don't expect those kwargs ;)

**Comment by danielballan** [comment]
I suspect you are right but I still don't follow. What happens when I call `insert_run_start` with a database keyword argument the first name? Please explain how correct usage works.

**Pull request merged**
