### PR TITLE
WIP: Fix typo

### PR DESCRIPTION
**Pull request by ericdill**
Also need to add a test to make sure that I hit this code path

### CODE REVIEW

**Comment by danielballan** [comment]
Nice catch. Will wait for test to merge.

**Comment by ericdill** [comment]
@danielballan added the smoketest to hit that line that had the typo. Merge away

**Comment by danielballan** [comment]
Travis blew up.

**Comment by ericdill** [comment]
Why so it did.

What is the purpose of [this test fixture] (https://github.com/NSLS-II/filestore/blob/master/filestore/test/test_fs.py#L43)?  It does not get used, as there `install_sentinels` is not defined in `test_fs.py` and so would blow up if it was used.

**Comment by ericdill** [comment]
gah nevermind. Now I see it.  That's what #104 fixed

**Pull request merged**
