### PR TITLE
Add API necessary for supporting export from one FileStore to another.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by tacaswell** [comment]
On consideration, dropping all of the `datumkw` family of functions / methods is a good idea.  Just nuke them and clean up the mess :smiling_imp: .

**Comment by danielballan** [comment]
Done.

**Comment by tacaswell** [comment]
Do we have an api changes log for this repo yet?

**Comment by danielballan** [comment]
Nope, I checked. Still holding out for the possibility that someone else might have and write docs. ;- )

**Comment by danielballan** [comment]
We have made API changes in the past...

    ENH: Add copying, get datums, and get files to public API.
     - extended public API to get the ``Resource`` from a datum eid via `resource_given_eid`.
    API: map `None` -> `''` in insert_resource
    API: ensure v1 works with v0 documents
    API: datum_kwargs in insert_datum must not be None
    API: do not leak mongo details out of public API
    API: change get_datum -> retrieve
     - brings the object API in line with
    API/ENH: add version sentinel collections
    API: change chroot -> root everywhere
    API: add chroot to resource
    API: change schema to use uid for foreign keys
    DOC: bit more thought about API changes
    MNT: use ChainMap API a bit more natuarally
    MNT: use ChainMap API a bit more natuarally
    MNT/API: simplify handler registry
    Merge pull request #76 from tacaswell/API_restore_handlersbase
    FIX/API: restore HandlerBase at top level
    FIX/API: restore HandlerBase at top level
    API: do not import conf in __init__.py
    REF/API: remove handler_registry from sigs
     - core.get_datum loses 3rd arg.  This is a major API break, but
    API: DatumNotFound does not inherit Datum.DoesNotExist
     - not intended for end-users, but part of public developer API
    API/MNT: start to pick apart get_data
    MNT/API: move Handler base classes out of retrieve
     - re-import to maintain API, but will remove eventually
    API/REF: don't return ME obj from isert_resource
    This should have minimal API breakage as nothing should have been using
    API: unbreak it
    PRF/API: speed up retrieve
    PRF/API: speed up retrieve
    documents.  This should not matter as the public API is un-changed.
    API : Config overhaul
    API : change how configuration data is loaded
    Matches (more-or-less) API in MDS again.
     - Major renaming/API changes
      - completely redid user API
    API : add specs values to handlers
    API : moved contents of spec.py into odm_templates
    API : fix spelling in class name
    API : remove ResourceAttribute collection
    pinned with maintaining the current API
    API : lock down the allowed properties
    MNT/API : make schema docs valid jsonsechma documents
    MNT/API : update spe handler to match collection
    API : added single file handler for spe files
    MNT/API : pims-ify PrincetonSPEFile
    API : Add fs_setup and fs_teardown testing utilities.
    API: Add fs_setup and fs_teardown testing utilities.
    API: Minor tweaks
    MNT/API : expose symmetric db_{connect,disconnect}
    MNT/API : expose symmetric db_{connect,disconnect}
    REF: Use public API in test.
    API: Add db_disconnect to API.
    API : Accept None as resource_path.
    API: Accept None as resource_path.
    API: Add deregister_handler to API.
    API: Add deregister_handler to API.
    API : Add register_handler with the API.
    API: Add register_handler with the API.
    WIP : API renaming and clean up
    API : rename retrieve_datum -> retrieve
    Simplify naming on out-going API
    API/MNT : fix spelling error in ResourceAttribute
    API : change event_id -> datum_id
    API/SP : dattum -> datum
    API : rename Resource.{custom -> resource_kwargs}
    API : change file_path -> resource_path
    API : rename link_parameters -> dattum_kwargs
    API : rename nugget -> dattum
    API : merge all api into a single file
    API : removed find_nugget, find_resource
    API : removed collection_version
    API : removed un-needed API functions
    These examples do not show how to use the API correctly.
    API : rename FileAttributes
    API : rename FileEventLink
    API : change FileBase -> Resource
    API : move odm templates

... but now's as good as time as any to start tracking them in a document, per @tacaswell. Done.

**Pull request merged**
