### PR TITLE
PRF/API: speed up retrieve

### PR DESCRIPTION
**Pull request by tacaswell**
This speeds up datum retival by a factor of 30 by greedily caching
the datum documents the first time we see a resource.  By doing this
we greatly reduce the number of sockets that need to be created.

This changes the internal api of Retrive to no longer take mongoengine
documents.  This should not matter as the public API is un-changed.

### CODE REVIEW

**Comment by ericdill** [comment]
Looks good on a first pass. I'll dig into this first thing tomorrow. Have you tried this at hxn?

**Comment by tacaswell** [comment]
no, and I have a few more commits that need to escape my laptop

**Comment by ericdill** [comment]
cc @hanfeiyan @skalbfleisch @klauer 

I am currently ssh'd in to xf03idc-ws2.  With this filestore branch:
```
In [3]: filestore.__version__
Out[3]: '0.1.0.post0'

In [4]: %timeit ss1395 = ss[1395]
1 loops, best of 3: 10.4 s per loop
```

With the filestore that is currently installed at hxn:
```
In [1]: import filestore

In [2]: filestore.__version__
Out[2]: 'v0.0.4'

In [3]: %timeit ss1395 = ss[1395]
1 loops, best of 3: 1min 48s per loop
```

Note that if you don't need to grab the MCA data (or any data that is stored in filestore for that matter) there is a stateful flag on the StepScap interface that turns on/off filestore data retrieval (which speeds up data access by an order of magnitude):

```
In [16]: ss.fill_events = False

In [17]: %timeit ss1395 = ss[1395]
1 loops, best of 3: 1.16 s per loop

In [18]: filestore.__version__
Out[18]: '0.1.0.post0'
```
and currently installed filestore
```
In [4]: ss.fill_events = False

In [5]: %timeit ss1395 = ss[1395]
1 loops, best of 3: 1.11 s per loop

In [6]: filestore.__version__
Out[6]: 'v0.0.4'
```

**Comment by klauer** [comment]
Certainly an improvement! 

For reference, scan 1395 is 3721 points. At 10.4 seconds, this means with filling events (i.e., grabbing the spectra) retrieval takes on average 2.8ms per scan point -- and without filling events, 0.3ms. Using that to estimate how long a 65k point scan would take yields around 3 minutes (~20 seconds without spectra).

**Comment by ericdill** [comment]
Can you give me scan_id's for larger data sets?

**Comment by tacaswell** [comment]
There is definitely still space to make this go faster.  Doing this one
bottle neck at a time.

I hope there is still one more easy 10x in there, but would not super
surprised if there is not.

This should also be bench marked using big data files on local disk to sort
out how much of the time is due to NFS issues.

Not using StepScan and working with the data a bit more directly would also
help.

**Comment by klauer** [comment]
@ericdill  Try using scan_id 1994 (note that there are two of these, likely due to concurrent ophyd sessions, so use the second one: `db.find_headers(scan_id=1994)[1]`) - it's 65001 points.

**Comment by ericdill** [comment]
There does not appear to be a significant difference between turning the events into a list versus shoving them into a dataframe

```
In [11]: len(list(db.fetch_events(db[2004], fill=False)))
Out[11]: 14641

In [12]: %timeit len(list(db.fetch_events(db[2004], fill=False)))
1 loops, best of 3: 5.1 s per loop

In [13]: %timeit ss2004 = ss[2004]
1 loops, best of 3: 5.23 s per loop
```

**Comment by ericdill** [comment]
Ah, thanks for that @klauer , I was only finding 81 points for id=1994 -_-

**Comment by ericdill** [comment]
~20 seconds is a good estimate. Here are the actual times
```
In [22]: %timeit len(list(db.fetch_events(list(db.find_headers(scan_id=1994))[1], fill=False)))
1 loops, best of 3: 18.4 s per loop

In [23]: len(list(db.fetch_events(list(db.find_headers(scan_id=1994))[1], fill=False)))
Out[23]: 65001
```

**Comment by klauer** [comment]
@ericdill No problem, it caused a fair bit of confusion on our end as well...

@tacaswell I'd guess you're right in that loading a bunch of files over NFS is largely to blame. Sometimes the scientists will want to load those 2D pixel array detector images, other times not. What do you think about having 'fill' allow a list of keys that we do want to load instead of the current all or none approach?

**Comment by danielballan** [comment]
I don't think passing a list to fill is the right approach. A results set
that mixes filled and unfilled data is bound to confuse people. ("Why are
some of my images random string?!" Haha.)

Instead, I'd like people to use an object that fills on demand. This
interface exists <http://soft-matter.github.io/pims>, and it's even set up
to understand Headers from the broker
<https://github.com/NSLS-II/dataportal/blob/master/dataportal/broker/pims_readers.py#L10>,
but you need the master branch of pims (that first link) to use it. Tagging
a release of pims and documenting this new way of doing things is a
priority. Making this lazy-loading behave ideally for every beamline's use
cases will take some fiddling.

Dan

**Comment by klauer** [comment]
That sounds like a nice, general solution. 

That said, most of our custom analysis/display utilities know exactly which fields they need to load, which was why I suggested the simple fix above.

**Comment by tacaswell** [comment]
We should add a way to pass through fetch events a list of the fields you want to see in the end result (and we can even make mongo do the filtering for us!).

**Comment by danielballan** [comment]
@klauer OK, good point, thanks for explaining your use case more.

To build on Tom's suggestion, we should add a data-focused alternative of `fetch_events`, a function that returns a generator that iterates through `event['data']` for each `event`, with optional mongo-level filtering on which fields of the `data` dict you want.

```
data = get_data(header)  # returns a generator (is fast)
```

or

```
data = get_data(header, ['det1', 'det2'])  # returns a generator (is fast)
```

Then

```
for d in data:
    # dispatch each detector's data to whatever utility processes it
    f(d['det1'])
    g(d['det2'])
```

`get_data` could also have an optional `fill` arg, but I think that would only be used for benchmarking/debugging, rarely for normal use.

Is this on the right track, @klauer?

**Comment by klauer** [comment]
@danielballan I think that sounds good. It does make more sense to offer, as you say, a data-focused alternative to `fetch_events` (rather than building in the functionality there).

**Comment by tacaswell** [comment]
I am wary of an interface which provides data without any of the identifying meta-data (ex event id, run id, event descriptor id, ....)

**Comment by tacaswell** [comment]
@ericdill can this be merged?

**Comment by danielballan** [comment]
@tacaswell Would you tag a micro release of filestore so we can roll this out?

**Pull request merged**
