### PR TITLE
WIP : API renaming and clean up

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by danielballan** [comment]
As we discussed on the train, I like "resource" for FileBase. I think "nugget" is a decent term for "smallest bit of data you can request at one time."

However it bothers me that in the current scheme, retrieve_data and insert_nugget are not symmetric. I am sure what I want to do about it. retrieve_nugget seems a little obscure. Thoughts?

**Comment by stuwilkins** [comment]
-1 on nugget ….. Too macdonalds. What about “datum”, my classic british education likes that more. I think where possible *datum* / *data* are useful because they mean singular and plural. I also like using *quantum* for the smallest possible chunk of data. Overall this is more professional.

S


On Feb 21, 2015, at 9:38 AM, Dan Allan <notifications@github.com<mailto:notifications@github.com>> wrote:


As we discussed on the train, I like "resource" for FileBase. I think "nugget" is a decent term for "smallest bit of data you can request at one time."

However it bothers me that in the current scheme, retrieve_data and insert_nugget are not symmetric. I am sure what I want to do about it. retrieve_nugget seems a little obscure. Thoughts?

**Comment by danielballan** [comment]
Ok we talked about datum but, lacking a classic British education, fell
back on American fast food. We aren't Eton men here.

+1 on datum, as long as you don't think it suggests "scalar."

**Comment by stuwilkins** [comment]
LOL……

I am not that classic, I grew up in the sticks in Scotland!

I don’t think datum at all suggests “scalar” in any way, at least not to me.

S

On Feb 21, 2015, at 9:52 AM, Dan Allan <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok we talked about datum but, lacking a classic British education, fell
back on American fast food. We aren't Eton men here.

+1 on datum, as long as you don't think it suggests "scalar."

**Comment by tacaswell** [comment]
I was more thinking 'nugget of gold', but will rename 'nugget' -> 'dattum' and make the retrieval symmetric.  

Using a word I apparently can not consistently spell correctly as a key component of the API was less than fully clever.

**Comment by ericdill** [comment]
Do you want to update the current examples based on the refactor?  I dont think they will work any longer with this refactor

**Comment by danielballan** [comment]
@ericdill I have a branch that takes care of these updates. Will push later this morning.

**Pull request merged**
